### ISSUE TITLE
Failed to activate the rest-client package

### ISSUE THREAD

**Issue by vvaka** [ddavison/rest-client#11]
[Enter steps to reproduce below:]

1. ...Upgrade from 0.190 to 0.192
2. ...

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [rest-client](https://github.com/ddavison/rest-client) package, v0.3.1

### Stack Trace

Failed to activate the rest-client package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.activate (/Users/vvaka/.atom/packages/rest-client/lib/rest-client.coffee:26:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:298:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
angularjs-snippets, v0.10.2
autocomplete-plus, v2.9.0
file-icons, v1.5.4
git-difftool, v0.2.5
go-oracle, v0.2.0
go-plus, v3.3.6
ionic-atom, v0.3.1
ionic-framework-snippets, v1.1.0
language-groovy, v0.4.0
language-scala, v1.1.0
monokai, v0.14.0
rest-client, v0.3.1
save-session, vundefined
sublime-tabs, v0.5.3

# Dev
No dev packages
```

**Comment by ddavison** [comment]
I had a similar issue created in https://github.com/ddavison/sublime-tabs. I fixed that one by updating all packages, and restarting atom. could you see if that fixes your issue?
