### ISSUE TITLE
Uncaught SyntaxError: Unexpected token a

### ISSUE THREAD

**Issue by bmrinal** [ddavison/rest-client#44]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [rest-client](https://github.com/ddavison/rest-client) package, v1.2.0

### Stack Trace

Uncaught SyntaxError: Unexpected token a

```
At file:///Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22initialPaths%22%3A%5B%22%2FVolumes%2FData%2Fusers%2Fmrinal%2Fprojects%2Fmangoapi%22%5D%2C%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FVolumes%2FData%2Fusers%2Fmrinal%2Fprojects%2Fmangoapi%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22%2FUsers%2Fmrinal%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Finitialize-application-window.js%22%2C%22resourcePath%22%3A%22%2FUsers%2Fmrinal%2FDownloads%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22clearWindowState%22%3Afalse%2C%22appVersion%22%3A%221.8.0%22%2C%22atomHome%22%3A%22%2FUsers%2Fmrinal%2F.atom%22%7D:1

SyntaxError: Unexpected token a
    at Object.parse (native)
    at RestClientView.module.exports.RestClientView.getRequestBody (/Users/mrinal/.atom/packages/rest-client/lib/rest-client-view.coffee:293:27)
    at RestClientView.module.exports.RestClientView.getRequestOptions (/Users/mrinal/.atom/packages/rest-client/lib/rest-client-view.coffee:263:14)
    at RestClientView.module.exports.RestClientView.sendRequest (/Users/mrinal/.atom/packages/rest-client/lib/rest-client-view.coffee:238:24)
    at HTMLButtonElement.<anonymous> (/Users/mrinal/.atom/packages/rest-client/lib/rest-client-view.coffee:167:43)
    at space-pen-div.jQuery.event.dispatch (/Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Users/mrinal/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -6:04.4.0 core:cut (textarea.field.rest-client-headers)
     -6:02.6.0 core:select-all (textarea.field.rest-client-payload)
     -6:02.0 core:paste (textarea.field.rest-client-payload)
  2x -5:51.7.0 core:cancel (textarea.field.rest-client-payload)
     -5:05.3.0 core:select-all (textarea.field.rest-client-payload)
     -5:04.3.0 core:cut (textarea.field.rest-client-payload)
     -4:51.3.0 rest-client:show (atom-text-editor.editor.power-mode.is-focused)
     -4:42.1.0 core:paste (textarea.field.rest-client-payload)
  2x -2:37.3.0 core:save (textarea.field.rest-client-payload)
     -2:32.1.0 core:select-all (textarea.field.rest-client-payload)
  2x -2:31.7.0 core:copy (textarea.field.rest-client-payload)
     -2:24.3.0 rest-client:show (atom-text-editor.editor.power-mode.is-focused)
     -2:19.4.0 core:select-all (textarea.field.rest-client-headers)
     -2:16.1.0 core:paste (textarea.field.rest-client-payload)
     -1:57.5.0 settings-view:open (div.rest-client.native-key-bindings.padded.pane-item)
     -1:15.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "rest-client": {}
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
atom-beautify, v0.29.10
atom-formatter-jsbeautify, v1.1.2
formatter-jsbeautify, v1.0.2
rest-client, v1.2.0

# Dev
No dev packages
```

**Comment by ddavison** [comment]
something like this would happen when you have the "application/json" mime type selected, but your API that you are requesting is returning borked JSON.  

look into the api you are polling from.. take the result and put it through http://jsonlint.com.  you'll see that it's invalid.

**Comment by bmrinal** [comment]
no the problem is actually in the payload parsing. If the payload is not a valid JSON, it breaks and gives me this error. API is fine. API is not even called. It breaks before that.

Can't we can have a graceful warning saying that the payload is invalid or something instead of this long error.

**Comment by ddavison** [comment]
could you tell me the method you are using?  I tried doing a POST request using `{ "some inv"alid json }` and didn't get an error.  how exactly are you sending the request

**Comment by bmrinal** [comment]
method i am using is "application/json". My payload was {somekey:"somevalue"}. So the quotes were missing around the keys. As soon as I got the quotes wrapped, it worked.

There is one more issue. Saved searches just disappear next day! Maybe I should open another issue for the same.

**Comment by javaguirre** [comment]
We should return a human message if the json is not correct in the response
