### ISSUE TITLE
Uncaught TypeError: Cannot read property 'headers' of null

### ISSUE THREAD

**Issue by mairanteodoro** [ddavison/rest-client#70]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [rest-client](https://github.com/ddavison/rest-client) package, v1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'headers' of null

```
At /Users/mairan/.atom/packages/rest-client/lib/rest-client-view.coffee:205

TypeError: Cannot read property 'headers' of null
    at RestClientView.module.exports.RestClientView.constructFileName (/Users/mairan/.atom/packages/rest-client/lib/rest-client-view.coffee:205:45)
    at RestClientView.module.exports.RestClientView.openInEditor (/Users/mairan/.atom/packages/rest-client/lib/rest-client-view.coffee:201:48)
    at HTMLSpanElement.<anonymous> (/Users/mairan/.atom/packages/rest-client/lib/rest-client-view.coffee:175:48)
    at space-pen-div.jQuery.event.dispatch (/Users/mairan/.atom/packages/rest-client/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/Users/mairan/.atom/packages/rest-client/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -8:39.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -7:12 core:save (atom-text-editor.editor.is-focused)
     -5:51.7.0 linter:lint (atom-text-editor.editor.is-focused)
  3x -5:44.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:37 core:save (atom-text-editor.editor.is-focused)
     -5:36.7.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:31.5.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
     -0:29.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:29.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 editor:log-cursor-scope (atom-text-editor.editor.is-focused)
     -0:27.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:26.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:23.7.0 rest-client:show (atom-text-editor.editor)
     -0:12.6.0 core:paste (input.field.rest-client-url)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-typescript, v10.1.9 (active)
autoclose-html, v0.23.0 (active)
autocomplete-python, v1.8.6 (active)
double-tag, v0.4.0 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.22 (active)
fold-comments, v0.6.0 (inactive)
genesis-ui, v0.5.0 (inactive)
linter, v1.11.18 (active)
open-recent, v5.0.0 (active)
open-unsupported-files, v1.0.19 (active)
platformio-ide-terminal, v2.2.0 (active)
project-manager, v3.2.5 (active)
rest-client, v1.3.1 (active)
sass-autocompile, v0.13.1 (active)
Sublime-Style-Column-Selection, v1.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by akapa100** [comment]
I have the same problem

**Comment by leonardlepadatu** [comment]
Same problem here when trying to:

## Open in separate editor ##

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [rest-client](https://github.com/ddavison/rest-client) package 1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'headers' of null

```
At /home/leo/.atom/packages/rest-client/lib/rest-client-view.coffee:205

TypeError: Cannot read property 'headers' of null
    at RestClientView.module.exports.RestClientView.constructFileName (/packages/rest-client/lib/rest-client-view.coffee:205:45)
    at RestClientView.module.exports.RestClientView.openInEditor (/packages/rest-client/lib/rest-client-view.coffee:201:48)
    at /packages/rest-client/lib/rest-client-view.coffee:175:48)
    at HTMLDivElement.dispatch (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:13.8.0 rest-client:show (input.hidden-input)
     -0:51.1.0 tabs:split-right (div.title)
     -0:45.2.0 tabs:split-left (div.title)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-html-preview 0.2.2 
atom-react-preview 2.0.0 
atom-shortcuts 0.0.2 
emmet 2.4.3 
highlight-selected 0.13.1 
language-babel 2.77.0 
markdown-preview-plus 2.4.16 
project-manager 3.3.5 
project-plus 1.0.0 
rest-client 1.3.1 
trailing-spaces 0.4.0 
```
