### ISSUE TITLE
Uncaught Error: HTTP HEAD requests MUST NOT include a request body.

### ISSUE THREAD

**Issue by alexandrefaustino** [ddavison/rest-client#83]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Linux Mint
**Thrown From**: [rest-client](https://github.com/ddavison/rest-client) package 1.3.1

### Stack Trace

Uncaught Error: HTTP HEAD requests MUST NOT include a request body.

```
At /usr/share/atom/resources/app.asar/node_modules/request/index.js:50

Error: HTTP HEAD requests MUST NOT include a request body.
    at request (/app.asar/node_modules/request/index.js:50:11)
    at Function.module.exports.RestClientHttp.send (/packages/rest-client/lib/rest-client-http.coffee:22:5)
    at RestClientView.module.exports.RestClientView.sendRequest (/packages/rest-client/lib/rest-client-view.coffee:252:22)
    at /packages/rest-client/lib/rest-client-view.coffee:169:43)
    at HTMLDivElement.dispatch (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/platformio-ide-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -9:04.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
file-icons 2.1.41 
highlight-selected 0.17.0 
hyperclick 0.1.5 
rest-client 1.3.1 
script 3.26.0 
terminus 4.0.5 
```

**Comment by ddavison** [comment]
Closed from https://github.com/ddavison/rest-client/pull/86
